/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import edu.princeton.cs.algs4.StdIn;
import edu.princeton.cs.algs4.StdOut;
import edu.princeton.cs.algs4.StdRandom;

public class App {

    public static void main(String[] args) {
        String champion = "";
        String inputWord;
        int wordNum = 1;
        while(!StdIn.isEmpty()){
            inputWord = StdIn.readString();
            if(StdRandom.bernoulli((double)1/(wordNum))){
                champion = inputWord;
            }
            wordNum++;
        }
        StdOut.println(champion);
    }
}
